project:
  type: website

website:
  title: "rtichoke"
  sidebar:
    - id: user-guide
      title: "User Guide"
      style: "docked"
      contents:
        - text: "Getting Started"
          href: tutorials/getting_started.qmd
    - id: api-reference
      title: "API Reference"
      style: "docked"
      contents:
        - href: reference/index.qmd
          text: "Reference"

quartodoc:
  package: rtichoke
  sections:
    - title: Performance Data
      desc: Functions for creating performance data.
      contents:
        - prepare_performance_data
        - prepare_performance_data_times
    - title: Discrimination
      desc: Functions for Discrimination.
      contents:
        - create_roc_curve
        - create_precision_recall_curve
        - create_gains_curve
        - create_lift_curve
        - plot_roc_curve
        - plot_precision_recall_curve
        - plot_gains_curve
        - plot_lift_curve
    - title: Utility
      desc: Functions for Utility.
      contents:
        - create_decision_curve
        - plot_decision_curve
