project:
  type: website

metadata-files:
  - _sidebar.yml

website:
  title: "rtichoke"
  navbar:
    left:
      - href: reference/
        text: Reference

quartodoc:
  # the name used to import the package you want to create reference docs for
  package: rtichoke
  sidebar: "_sidebar.yml"
  sections:
    - title: Performance Data
      desc: Functions for creating performance data.
      contents:
        - prepare_performance_data
        - prepare_performance_data_times
    # - title: Calibration
      # desc: Functions for Calibration.
      # contents:
        # - create_calibration_curve
    - title: Discrimination
      desc: Functions for Discrimination.
      contents:
        - create_roc_curve
        - create_precision_recall_curve
        - create_gains_curve
        - create_lift_curve
        - plot_roc_curve
        - plot_precision_recall_curve
        - plot_gains_curve
        - plot_lift_curve
    - title: Utility
      desc: Functions for Utility.
      contents:
        - create_decision_curve
        - plot_decision_curve